#!/usr/bin/env bash
set -e

# get the number from args if provided
number=$1

# if no number is provided, get the number from the current PR
if [ -z "$number" ]; then
    number=$(gh pr view --json number --jq '.number')
fi

if [ -z "$number" ]; then
    echo "No PR number provided"
    exit 1
fi

# Extract the body from the output
body=$(gh pr view "$number" --json body --jq '.body')

# Update all occurences of `${prNumber}` in the body with the actual number
updated_body=$(echo "$body" | sed "s/\${prNumber}/$number/g")

# check if the body has changed
if [ "$body" != "$updated_body" ]; then
    # Update the PR body with the new content
    gh pr edit "$number" --body "$updated_body"
fi
