#!/usr/bin/env bash
set -e

out=$(gh pr view --json number --json body)

# Extract the number from the output
number=$(echo "$out" | jq -r '.number')

# Extract the body from the output
body=$(echo "$out" | jq -r '.body')

# Update all occurences of `${prNumber}` in the body with the actual number
updated_body=$(echo "$body" | sed "s/\${prNumber}/$number/g")

# Update the PR body with the new content
gh pr edit "$number" --body "$updated_body"
